spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: baidu
        uri: http://www.baidu.com/
        predicates:
        - Path= /baidu/**
      - id: user
        uri: lb://CLOUD-USER
        predicates:
        - Path= /CLOUD-USER/**
      - id: config
        uri: lb://CLOUD-CONFIG
        predicates:
        - Path= /CLOUD-CONFIG/**
      - id: box
        uri: lb://CLOUD-BOX
        predicates:
        - Path= /CLOUD-BOX/**

