spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: baidu
        uri: http://www.baidu.com/
        predicates:
        - Path= /baidu/**
      - id: user
        uri: http://localhost:8060/
        predicates:
        - Path= /user/**
      - id: config
        uri: http://localhost:8000/
        predicates:
        - Path= /config/**
      - id: box
        uri: http://localhost:8070/
        predicates:
        - Path= /box/**

